source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Nimble', git: 'https://github.com/Quick/Nimble', branch: 'swift-2.0'
pod 'Quick', git: 'https://github.com/Quick/Quick', branch: 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'